services:
  - type: web
    name: e-kampot-shop
    runtime: docker
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: E-Kampot Shop
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: BROADCAST_DRIVER
        value: log
      - key: MAIL_MAILER
        value: smtp
      - key: VITE_APP_NAME
        value: E-Kampot Shop
    buildFilter:
      paths:
        - app/**
        - bootstrap/**
        - config/**
        - database/**
        - public/**
        - resources/**
        - routes/**
        - storage/**
        - artisan
        - composer.json
        - composer.lock
        - package.json
        - package-lock.json
        - build.sh
        - render.yaml
      ignoredPaths:
        - node_modules/**
        - vendor/**
        - .git/**
        - tests/**
        - .env*
        - README.md
